pipeline {
    agent {
        agent any
        
    }
    stages
    {
        stage("buid"){
            steps{
            
            sh'mvn build'
            
            }
        
        
        }
    
    
    
    
    }
       
}
